version: '2.1'

services:
  verable.beacon:
    image: verable.beacon
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 7001:7001
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js